### ISSUE TITLE
Large memory consumption, why?

### ISSUE THREAD

**Issue by mattes3** [IceCreamYou/THREE.Terrain#25]
I created a small test project here: https://github.com/mattes3/three-terrain-experiment.git
You can clone it, then make it run using these commands:
```bash
yarn
yarn serve
```

Then, open http://localhost:5000

On my machine (Mac OS X 10.14.5 with Chrome 75.0.3770.142) this takes lots of memory:

| Terrain size | Memory of Chrome process |
| ------------- | ------------- |
| 511  | 543 MB  |
| 1023  | 1920 MB  |

(I got these numbers from the "top" program that is contained in Mac OS X).

This would mean that each "pixel" of the terrain costs 1753 Bytes! I expected only one triangle per pixel, that means 3 vertices * 3 coords * 8 bytes per coord = 72 Bytes per triangle!

Can you help me understand why it is 1753 and not 72?

My assumptions:

* Going from 511 to 1023, the number of "pixels" increases by 1023 * 1023 - 511 * 511=785408
* The amount of memory increased by 1377 MB.
* So, each "pixel" must have consumed 1377000000/785408=1753 bytes.

**Comment by IceCreamYou** [comment]
This doesn't really seem like a `THREE.Terrain` question - I expect you'd have similar results if you created a scene with the same objects without this library. In general, three.js geometry objects can get pretty big. What's in memory is not just the screen buffer, it's all the references to faces, points, etc. that are required to calculate the scene. Browser dev tools have built in profilers these days that you could use to see which objects take up the most memory.

One thing worth noting is that `THREE.Terrain` might temporarily increase memory usage when applying certain transformations to the plane, as it needs to copy some things in order to do certain calculations, but references to those objects aren't kept and so the allocated memory should be garbage collected within a few seconds.

**Comment by mattes3** [comment]
In the meantime, I have been analyzing other options for building terrain because the memory consumption was killing my app.

I found out that I can build the terrain on the GPU instead of the CPU. As an example, I built a 4096x4096 terrain using only a heightmap of 64MB in size (4 bytes per texel in GPU framebuffer memory, not in CPU memory). Not a single triangle in sight ... it takes only a 10th of a second to build (once, only), and later in the animation loop, the terrain looks really good! These GPUs are sooooo fast, several teraflops of performance, amazing!

The approach looks so promising that I think I will turn away from using ThreeJS and terrain geometry at all. Success, however, will really depend on how texture mapping, lighting, and shadows will work out with this "no geometry" approach. Will keep you updated.
