### ISSUE TITLE
Three.js v 71

### ISSUE THREAD

**Issue by vladgaidukov** [IceCreamYou/THREE.Terrain#3]
Hi, library does not work with current three.js v71

**Comment by IceCreamYou** [comment]
I just committed a fix for this and tagged a new release (1.2.1) with the fix.

Neither r70 nor r71 had documented changelogs, and there are over 1000 commits between r69 and master. It's hard to keep up with a project that active without a changelog!

The problem was that custom blended textures don't render. The terrain generation itself was fine. Apparently the GLSL code for material shaders was refactored somewhat, across several PR's, particularly around lighting.

For future reference, "it doesn't work" is not a helpful report. It helps to explain exactly what doesn't work and any errors you get. :smiley:

**Comment by vladgaidukov** [comment]
Thank you!
